# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/focal64"

  ## how linux works environment
  config.vm.define :linux_works do |lw_config|
    lw_config.vm.box = "ubuntu/focal64"
    lw_config.vm.hostname = "linux-works"
    lw_config.vm.network :private_network, :ip => "192.168.33.10"
  end

end
